### ISSUE TITLE
Extending jsonplus

### ISSUE THREAD

**Issue by karolyi** [randomir/jsonplus#1]
Hey,

I use `django-money`, and I'd like to serialize `Money` objects back and forth. Looking into your code, I see no feasible solution as to extending the `_json_object_hook` for the decoder and `_json_default_compat` for the encoder.

If they would be class based, I would be able to subclass them and then add my functionality on top.

Do you have any suggestion on how to achieve extending those two functions?

Cheers,
László

**Comment by karolyi** [comment]
So after looking at your code, I put together a module that extends yours. Needless to say, it got convoluted because there's no easy way of extending jsonplus. Here it is:

```python
from functools import lru_cache
from types import FunctionType

from djmoney.money import Money
from jsonplus import _encoder_default_args, _json_object_hook
from moneyed import EUR
from simplejson import JSONDecoder as SimpleJSONDecoder
from simplejson import JSONEncoder as SimpleJSONEncoder
from simplejson import dumps as simple_dumps
from simplejson import loads as simple_loads


def dump_money(money: Money) -> list:
    """Dump a `Money` instance into JSON format."""
    if money.currency == EUR:
        return [str(money.amount)]
    return [str(money.amount), money.currency.code]


def load_money(json: list) -> Money:
    """Load a `Money` instance from a JSON format."""
    if len(json) == 1:
        return Money(json[0], EUR)
    return Money(json[0], json[1])


def _my_json_default(orig_func: FunctionType) -> FunctionType:
    """Extend `jsonplus`'s functionality with project specific ones."""
    def overrider(obj):
        try:
            return orig_func(obj=obj)
        except TypeError:
            class_type = type(obj)
            if class_type is Money:
                return dict(__class__='Money', __value__=dump_money(money=obj))
            raise
    return overrider


def _my_json_object_hook(obj: dict):
    """Extend `jsonplus`'s functionality with project specific ones."""
    try:
        return _json_object_hook(dict=obj)
    except TypeError:
        classname = obj.get('__class__')
        if classname == 'Money':
            value = obj.get('__value__')
            return load_money(json=value)
        raise


class JSONEncoder(SimpleJSONEncoder):
    """A JSON encoder for objects used in the project."""

    def __init__(self, **kwargs):
        """
        Constructor for simplejson.JSONEncoder, with defaults overriden
        for jsonplus.
        """
        _encoder_default_args(kw=kwargs)
        kwargs['default'] = _my_json_default(orig_func=kwargs['default'])
        super().__init__(**kwargs)


class JSONDecoder(SimpleJSONDecoder):
    """A JSON encoder for objects used in the project."""

    def __init__(self, **kwargs):
        """
        Constructor for simplejson.JSONDecoder, with defaults overriden
        for jsonplus.
        """
        kwargs.update({'object_hook': _my_json_object_hook})
        super().__init__(**kwargs)


def loads(*args, **kwargs):
    kwargs['cls'] = JSONDecoder
    return simple_loads(*args, **kwargs)


def dumps(*args, **kwargs):
    kwargs['cls'] = JSONEncoder
    return simple_dumps(*args, **kwargs)


@lru_cache(maxsize=50)
def loads_cached(dump: str) -> dict:
    """Return (and cache) a loaded JSON state."""
    return loads(s=dump)
```

If you happen to come up with an easily extensible version of your module, I'd be happy to have it. I could do it as well, but I'm way too busy right now. Moreover, I use python3.6 and I don't really care about backwards compatibility. This implementation fits my needs just fine.

**Comment by randomir** [comment]
Hi László,

thanks for the suggestion. I've added support for `Money` and `Currency` objects (from `py-moneyed`/`django-money`) to `jsonplus` (v0.6.6).
Let me know if it works as expected!

Cheers,
Radomir

**Comment by karolyi** [comment]
Hey,

I did not test the code (just woke up), but looking into it, are you sure that `_json_default_compat` and `str` will result in a `Money` dump that will be decodable later?  Loading that string results in an error:

```ipython
In [21]: Money('0.00. EUR')
---------------------------------------------------------------------------
InvalidOperation                          Traceback (most recent call last)
<ipython-input-21-5f4c19cb15af> in <module>()
----> 1 Money('0.00. EUR')

~/project/venv/lib/python3.6/site-packages/moneyed/classes.py in __init__(self, amount, currency)
     81     def __init__(self, amount=Decimal('0.0'), currency=DEFAULT_CURRENCY_CODE):
     82         if not isinstance(amount, Decimal):
---> 83             amount = Decimal(str(amount))
     84         self.amount = amount
     85 

InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by karolyi** [comment]
There is another issue.

`django-money` uses a patched `Money` class that is `djmoney.money.Money` instead of `moneyed.Money`. The difference is significant: localization, html escaping, and a lot more things are going on in that class.

The problem is, jsonplus deserializes back to `moneyed.Money` instead of `djmoney.money.Money`, losing all the added functionality in the process.

Please differentiate between those two classes.

**Comment by randomir** [comment]
Hey László,

The "compat" mode exists so that all (supported) types can be dumped to JSON. For successful reconstruction, the decoding side has to put in a little bit of extra effort. For example, dates are serialized to plain ISO8601 strings, without the information about the type. Currently, `Money` is serialized as a plain `str` in compat mode.

Regarding the `djmoney.money.Money` class - I'm reluctant in putting that in the generic `jsonplus` package. It would probably make more sense to put Django-specific stuff to `django-jsonplus` package. I'll look into that. Btw, I see `django-money` already has some serialization support for Django -- have you tried using it?

**Comment by karolyi** [comment]
Hey Radomir,

no I haven't looked into it, but as far as I can see, it's just dumping the amount and currency values with the class name, fairly easy.

I still don't see how this has to interact with your module. In order to use this, you'll have to add the usage of deconstructibles for the dump.

So, do you plan to release a `django-jsonplus` version of this package?

Cheers,
László

**Comment by randomir** [comment]
Hey László,

I've just added predicate-based, prioritized, encoder definition support to `jsonplus` (v0.8, feel free to take a look and comment on those).

Now it's pretty simple to add a custom encoder, for example to support Django Money, see https://github.com/randomir/jsonplus/blob/master/python-django/django_jsonplus/coders.py

**Comment by karolyi** [comment]
Absolutely LGTM!

I can confirm, `jsonplus` as a module made a leap forward. The only comment I had, you can find on the line itself :)

I'll have to stick with my monkeypatch now as somehow it generates slightly different dumps, where the dumped json has extra spaces after the `:` and `,` signs, but that's just a minor issue, and may well be unrelated to your changes. Also, I had to roll out my work early, so I had no time to wait for your changes to arrive, unfortunately.

I pulled your module, adjusted my tests to see if they would work as expected, and they do. So this is a perfect addition to any future project, and I will definitely use it later on.

My only suggestion would be to break down your `__init__.py` to submodules as you're starting to reach 500 lines, but in general, you get a huge high5 from me, as a pythonista since 2002. :)

Cheers!

P.S.: Closing this issue as a perfectly solved one.

**Comment by randomir** [comment]
Thanks László, so nice to hear that. :)

Let me just touch on the spaces issue. You can control the spaces (or even change the `:`/`,` characters) via `separators` kwarg. For example, with `jsonplus`:
```
>>> import jsonplus
>>> d = {'a':1, 'b':2}
>>> jsonplus.dumps(d)
'{"a":1,"b":2}'
>>> jsonplus.dumps(d, separators=(', ', ': '))
'{"a": 1, "b": 2}'
>>> jsonplus.dumps(d, separators=(',', ':'))
'{"a":1,"b":2}'
>>> jsonplus.pretty(d)
'{\n    "a": 1,\n    "b": 2\n}'
>>> print(jsonplus.pretty(d))
{
    "a": 1,
    "b": 2
}
```

Default `separators=(',', ':')` produce compact representation, and they are defined in [`_encoder_default_args`](https://github.com/randomir/jsonplus/blob/master/python/jsonplus/__init__.py#L265). They can be overridden on each `dumps` call. [`pretty`](https://github.com/randomir/jsonplus/blob/master/python/jsonplus/__init__.py#L307) does that.

`simplejson` uses different default separators:
```
>>> simplejson.dumps(d)
'{"a": 1, "b": 2}'
>>> jsonplus.dumps(d)
'{"a":1,"b":2}'
```
but you can change them in the same way as above, via `separators` kwarg.

Regarding the `__init__.py` size -- completely agree, I have that refactor in mind. :)

Cheers!
